- name: Download Clean Gradle Wrapper JAR
  run: |
    mkdir -p gradle/wrapper
    curl -Lo gradle/wrapper/gradle-wrapper.jar https://raw.githubusercontent.com/gradle/gradle/v8.4.0/gradle/wrapper/gradle-wrapper.jar
